name: mangovox_md_notes
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_tabler_icons: ^1.43.0
  go_router: ^18.0.1
  get_it: ^9.2.1
  google_fonts: ^8.2.1
  flutter_svg: ^2.3.0
  flutter_secure_storage: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true

assets:
  - assets/icons/
  - assets/fonts/
